spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_db?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

  rabbitmq:
    host: 115.28.49.96
    port: 5672
    username: backend
    password: stylewe
    virtual-host: mrp